BEGIN;

CREATE TABLE planet (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  climate VARCHAR(45) NOT NULL,
  terrain VARCHAR(45) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UC_PLANET_NAME UNIQUE (name));

COMMIT;