BEGIN;

CREATE TABLE film (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  director VARCHAR(100) NOT NULL,
  release_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  CONSTRAINT UC_FILM_NAME UNIQUE (name));

COMMIT;